model:
  type: pyramid
  depth: 272
  alpha: 200
  bottleneck: True
dataset: cifar100
aug: custom
cutout: 16
batch: 64
epoch: 1800
lr: 0.05
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 1
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.00005
  ema: 0
exp:
  dir: experiments/py_c100