model:
  type: wresnet40_2
dataset: reduced_svhn
aug: custom
cutout: 20
batch: 128
epoch: 120
lr: 0.01
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 1
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005
  ema: 0