model:
  type: resnet18
dataset: reduced_cifar10
aug: custom
cutout: 16
batch: 128
epoch: 90
lr: 0.05
lr_schedule:
  type: 'resnet'
  milestones: [90, 180, 240]
  decay: 0.1
  warmup:
    multiplier: 1
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0001
  clip: 0
  ema: 0