dataset_name: GTZAN
data_dir: /data/torch/datasets/audio/GTZAN
dataaug: true
pretrained: true
scheduler: true
model: inception
batch_size: 32
num_workers: 16
epochs: 70
lr: 0.0001
weight_decay: 0.001
num_folds: 1
is_save: False
checkpoint_dir: checkpoints
window_sizes: [25, 50, 100]
hop_sizes: [10, 25, 50]
sample_rate: 22050
csv_file: ''
preprocess_csv_dir: /data/torch/datasets/audio/GTZAN/preprocessed
n_fft: 2205
reshape_length: 1500
num_channels: 3
reduced_train_size: 1
aug: ''
n: 1
m: 0.1
exp:
  dir: experiments/gtzan_inception