model:
  type: shakeshake26_2x96d
dataset: svhn
aug: custom
cutout: 20
batch: 128
epoch: 200
lr: 0.01
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 1
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.001
  ema: 0
exp:
  dir: experiments/ss_96_svhn