dataset_name: GTZAN
data_dir: /data/torch/datasets/audio/GTZAN
pretrained: true
scheduler: true
model: resnet
batch_size: 32
num_workers: 0
epochs: 5
lr: 0.0001
weight_decay: 0.001
num_folds: 1
is_save: False
checkpoint_dir: checkpoints
window_sizes: [25, 50, 100]
hop_sizes: [10, 25, 50]
sample_rate: 22050
csv_file: ''
preprocess_csv_dir: /data/torch/datasets/audio/GTZAN/preprocessed
n_fft: 2205
reshape_length: 1500
num_channels: 3
reduced_train_size: 0.3